package start

import (
	"fmt"
	"poshta/internal/app/config"
	"poshta/pkg/logger"
	"net/http"
	"github.com/sirupsen/logrus"
	"poshta/internal/handler"
	"poshta/internal/middleware"

	httpSwagger "github.com/swaggo/http-swagger"
	_ "poshta/docs" // docs is generated by Swag CLI, you have to import it.
)

func HTTP(cfg *config.Config, authHandeler *handlers.AuthHandler, jwtMiddleware *middleware.JWTMiddleware) {
	http.HandleFunc("/healthcheck", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("status: Its all good man"))
		logger.Info("Health check requested", nil)
	})
	
	http.HandleFunc("/swagger/", httpSwagger.WrapHandler)

	//auth routes
	http.HandleFunc("/api/auth/register", authHandeler.Register)
	http.HandleFunc("/api/auth/login", authHandeler.Login)
	http.HandleFunc("/api/auth/refresh", authHandeler.RefreshToken)

	// example of protected route with jwt middleware
	http.Handle("/api/protected", jwtMiddleware.CreateAuthenticatedHandler(authHandeler.GetProtectedResource))

	addr := fmt.Sprintf("%s:%d", cfg.HTTPServer.Host, cfg.HTTPServer.Port)
	logger.Info("Starting HTTP server", logrus.Fields{
		"address": addr,
		"swagger":  fmt.Sprintf("%s/swagger/index.html", addr),
	})

	if err := http.ListenAndServe(addr, nil); err != nil {
		logger.Error("HTTP server failed", err, nil)
	}
}
